### ISSUE TITLE
一定要用fim吗 我只用蒲公英就不行吗》

### ISSUE THREAD

**Issue by PengJiang520** [huangxuan518/HXPackRobot#10]
Traceback (most recent call last):
  File "/Users/jiangpeng/Desktop/PackRobot/pack.py", line 134, in <module>
    main()
  File "/Users/jiangpeng/Desktop/PackRobot/pack.py", line 127, in main
    upload_app()
  File "/Users/jiangpeng/Desktop/PackRobot/pack.py", line 76, in upload_app
    if (fir_api_token == "xxxxxxxxxxxxxxxxxxxxxxxxxxxx"):
NameError: global name 'fir_api_token' is not defined

**Comment by moonclock** [comment]
程序的上传方式判断依赖于fir_api_token的值,
只使用蒲公英,请保持 fir_api_token = "xxxxxxxxxxxxxxxxxxxxxxxxxxxx" # firm的api token
