### ISSUE TITLE
拿不到ipa的包 求大神的联系方式 请教下

### ISSUE THREAD

**Issue by PengJiang520** [huangxuan518/HXPackRobot#11]
curl: (26) couldn't open file "/Users/jiangpeng/Desktop/PackRobot/app_2017-08-23-19-53-17/app.ipa"
Traceback (most recent call last):
  File "/Users/jiangpeng/Desktop/PackRobot/pack.py", line 134, in <module>
    main()
  File "/Users/jiangpeng/Desktop/PackRobot/pack.py", line 129, in main
    send_mail()
  File "/Users/jiangpeng/Desktop/PackRobot/pack.py", line 102, in send_mail
    server = smtplib.SMTP(smtp_server, 25)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 291, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
jiangpengdeMacBook-Pro:~ jiangpeng$

**Comment by moonclock** [comment]
请检查/Users/jiangpeng/Desktop/PackRobot下是否有ipa 包,报错信息上看编译应该是成功了.
