### ISSUE TITLE
上传到蒲公英可以了 但是发送邮件失败 求解

### ISSUE THREAD

**Issue by hanxueshi** [huangxuan518/HXPackRobot#15]
send: 'AUTH PLAIN ADkxMzgzMTExMEBxcS5jb20Ad29zaGltYXlhbzExMA==\r\n'
reply: '535 Error: \xc7\xeb\xca\xb9\xd3\xc3\xca\xda\xc8\xa8\xc2\xeb\xb5\xc7\xc2\xbc\xa1\xa3\xcf\xea\xc7\xe9\xc7\xeb\xbf\xb4: http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256\r\n'
reply: retcode (535); Msg: Error: ??ʹ????Ȩ???¼???????뿴: http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256
Traceback (most recent call last):
  File "/Users/hanxueshi/Desktop/PackRobot/pack.py", line 134, in <module>
    main()
  File "/Users/hanxueshi/Desktop/PackRobot/pack.py", line 129, in main
    send_mail()
  File "/Users/hanxueshi/Desktop/PackRobot/pack.py", line 104, in send_mail
    server.login(from_addr, password)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 622, in login
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, 'Error: \xc7\xeb\xca\xb9\xd3\xc3\xca\xda\xc8\xa8\xc2\xeb\xb5\xc7\xc2\xbc\xa1\xa3\xcf\xea\xc7\xe9\xc7\xeb\xbf\xb4: http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256')

**Comment by moonclock** [comment]
可以参照issues4 中,我的回答来解决.
[issues4](https://github.com/huangxuan518/HXPackRobot/issues/4)

**Comment by moonclock** [comment]
#12
